### ISSUE TITLE
not execute the createsamples.pl

### ISSUE THREAD

**Issue by Jaylton** [mrnugget/opencv-haar-classifier-training#17]
When I execute:

perl bin/createsamples.pl positives.txt negatives.txt samples 1500\
"opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1\
-maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 80 -h 40"

Code runs, but it's not creating any files in "samples" folder.

Please help!!!

**Comment by mrnugget** [comment]
That's not nearly enough information.

What's the content of positives.txt? And what's in negatives.txt?

**Comment by Jaylton** [comment]
positive images in positives.txt and negative in negatives.txt

**Comment by MTRNord** [comment]
Simmilar error here: It works but the .vec files are completly empty

**Comment by Jaylton** [comment]
I could run, but in the code
python ./tools/mergevec.py -v samples/ -o samples.vec
shows this error:
Traceback (most recent call last):  
File "mergevec.py", line 170, in <module>  
merge_vec_files(vec_directory, output_filename)  
File "mergevec.py", line 133, in merge_vec_files  
val = struct.unpack('<iihh', content[:12])  

what's up?

**Comment by mrnugget** [comment]
My question was: what's the _content_ of positives.txt and negatives.txt. Like "what's actually in the file?"

**Comment by Jaylton** [comment]
the way to the negative and positive images:
./positive_images/20160726_110252.jpg
./positive_images/20160726_110258.jpg
./positive_images/20160726_110305.jpg
./positive_images/20160726_110310.jpg
./positive_images/20160726_110317.jpg
./positive_images/20160726_110342.jpg
it's worked, thanks, there was another error:
in step 7 shows this error:
  opencv_traincascade: command not found
because? and how to fix?

**Comment by mrnugget** [comment]
Did you install opencv?

**Comment by shakesyne** [comment]
@Jaylton how did you fix it?
I have also stuck that point.

**Comment by Jaylton** [comment]
@shakesyne https://github.com/wulfebw/mergevec

**Comment by johnd3v** [comment]
we have same problem man. i cant proceed to step 6 because there is no vec file created in step 5

**Comment by michaelvogt** [comment]
Yes, see the same problem, no .vec files in  sample folder
